{
 "title": "RTAP Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 *\r\nsum(rate(http_server_requests_seconds_count{status=~\"5..\"}[5m])) /\r\nsum(rate(http_server_requests_seconds_count[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 Latency (events)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (le) (\r\n    rate(http_server_requests_seconds_bucket{uri=\"/api/v1/events\"}[5m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Requests (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}